BEGIN TRANSACTION

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Orders')
BEGIN
    IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Orders_BAK')
    BEGIN
        DROP TABLE [dbo].[Orders_BAK]
    END
    EXEC dbo.asi_RenameTable 'Orders', 'Orders_BAK'
END

SET ANSI_DEFAULTS ON
SET IMPLICIT_TRANSACTIONS OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM [dbo].[sysobjects] WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[Orders](
    [ORDER_NUMBER] numeric(15,2) NOT NULL CONSTRAINT [DF_Orders_ORDER_NUMBER] DEFAULT (0),
    [ORG_CODE] varchar(5) NOT NULL CONSTRAINT [DF_Orders_ORG_CODE] DEFAULT (''),
    [ORDER_TYPE_CODE] varchar(10) NOT NULL CONSTRAINT [DF_Orders_ORDER_TYPE_CODE] DEFAULT (''),
    [STAGE] varchar(10) NOT NULL CONSTRAINT [DF_Orders_STAGE] DEFAULT (''),
    [SOURCE_SYSTEM] varchar(10) NOT NULL CONSTRAINT [DF_Orders_SOURCE_SYSTEM] DEFAULT (''),
    [BATCH_NUM] varchar(15) NOT NULL CONSTRAINT [DF_Orders_BATCH_NUM] DEFAULT (''),
    [STATUS] varchar(10) NOT NULL CONSTRAINT [DF_Orders_STATUS] DEFAULT (''),
    [HOLD_CODE] varchar(10) NOT NULL CONSTRAINT [DF_Orders_HOLD_CODE] DEFAULT (''),
    [ORDER_DATE] datetime NULL,
    [BT_ID] varchar(10) NOT NULL CONSTRAINT [DF_Orders_BT_ID] DEFAULT (''),
    [ST_ID] varchar(10) NOT NULL CONSTRAINT [DF_Orders_ST_ID] DEFAULT (''),
    [ST_ADDRESS_NUM] int NOT NULL CONSTRAINT [DF_Orders_ST_ADDRESS_NUM] DEFAULT (0),
    [ENTERED_DATE_TIME] datetime NULL,
    [ENTERED_BY] varchar(15) NOT NULL CONSTRAINT [DF_Orders_ENTERED_BY] DEFAULT (''),
    [UPDATED_DATE_TIME] datetime NULL,
    [UPDATED_BY] varchar(60) NOT NULL CONSTRAINT [DF_Orders_UPDATED_BY] DEFAULT (''),
    [INVOICE_REFERENCE_NUM] int NOT NULL CONSTRAINT [DF_Orders_INVOICE_REFERENCE_NUM] DEFAULT (0),
    [INVOICE_NUMBER] int NOT NULL CONSTRAINT [DF_Orders_INVOICE_NUMBER] DEFAULT (0),
    [INVOICE_DATE] datetime NULL,
    [NUMBER_LINES] int NOT NULL CONSTRAINT [DF_Orders_NUMBER_LINES] DEFAULT (0),
    [FULL_NAME] varchar(70) NOT NULL CONSTRAINT [DF_Orders_FULL_NAME] DEFAULT (''),
    [TITLE] varchar(80) NOT NULL CONSTRAINT [DF_Orders_TITLE] DEFAULT (''),
    [COMPANY] varchar(80) NOT NULL CONSTRAINT [DF_Orders_COMPANY] DEFAULT (''),
    [FULL_ADDRESS] varchar(255) NOT NULL CONSTRAINT [DF_Orders_FULL_ADDRESS] DEFAULT (''),
    [PREFIX] varchar(25) NOT NULL CONSTRAINT [DF_Orders_PREFIX] DEFAULT (''),
    [FIRST_NAME] varchar(20) NOT NULL CONSTRAINT [DF_Orders_FIRST_NAME] DEFAULT (''),
    [MIDDLE_NAME] varchar(20) NOT NULL CONSTRAINT [DF_Orders_MIDDLE_NAME] DEFAULT (''),
    [LAST_NAME] varchar(30) NOT NULL CONSTRAINT [DF_Orders_LAST_NAME] DEFAULT (''),
    [SUFFIX] varchar(10) NOT NULL CONSTRAINT [DF_Orders_SUFFIX] DEFAULT (''),
    [DESIGNATION] varchar(30) NOT NULL CONSTRAINT [DF_Orders_DESIGNATION] DEFAULT (''),
    [INFORMAL] varchar(20) NOT NULL CONSTRAINT [DF_Orders_INFORMAL] DEFAULT (''),
    [LAST_FIRST] varchar(30) NOT NULL CONSTRAINT [DF_Orders_LAST_FIRST] DEFAULT (''),
    [COMPANY_SORT] varchar(30) NOT NULL CONSTRAINT [DF_Orders_COMPANY_SORT] DEFAULT (''),
    [ADDRESS_1] varchar(40) NOT NULL CONSTRAINT [DF_Orders_ADDRESS_1] DEFAULT (''),
    [ADDRESS_2] varchar(40) NOT NULL CONSTRAINT [DF_Orders_ADDRESS_2] DEFAULT (''),
    [CITY] varchar(40) NOT NULL CONSTRAINT [DF_Orders_CITY] DEFAULT (''),
    [STATE_PROVINCE] varchar(15) NOT NULL CONSTRAINT [DF_Orders_STATE_PROVINCE] DEFAULT (''),
    [ZIP] varchar(10) NOT NULL CONSTRAINT [DF_Orders_ZIP] DEFAULT (''),
    [COUNTRY] varchar(25) NOT NULL CONSTRAINT [DF_Orders_COUNTRY] DEFAULT (''),
    [DPB] varchar(8) NOT NULL CONSTRAINT [DF_Orders_DPB] DEFAULT (''),
    [BAR_CODE] varchar(14) NOT NULL CONSTRAINT [DF_Orders_BAR_CODE] DEFAULT (''),
    [ADDRESS_FORMAT] tinyint NOT NULL CONSTRAINT [DF_Orders_ADDRESS_FORMAT] DEFAULT (0),
    [PHONE] varchar(25) NOT NULL CONSTRAINT [DF_Orders_PHONE] DEFAULT (''),
    [FAX] varchar(25) NOT NULL CONSTRAINT [DF_Orders_FAX] DEFAULT (''),
    [NOTES] text NULL,
    [TOTAL_CHARGES] money NOT NULL CONSTRAINT [DF_Orders_TOTAL_CHARGES] DEFAULT (0),
    [TOTAL_PAYMENTS] money NOT NULL CONSTRAINT [DF_Orders_TOTAL_PAYMENTS] DEFAULT (0),
    [BALANCE] money NOT NULL CONSTRAINT [DF_Orders_BALANCE] DEFAULT (0),
    [LINE_TOTAL] money NOT NULL CONSTRAINT [DF_Orders_LINE_TOTAL] DEFAULT (0),
    [LINE_TAXABLE] money NOT NULL CONSTRAINT [DF_Orders_LINE_TAXABLE] DEFAULT (0),
    [FREIGHT_1] money NOT NULL CONSTRAINT [DF_Orders_FREIGHT_1] DEFAULT (0),
    [FREIGHT_2] money NOT NULL CONSTRAINT [DF_Orders_FREIGHT_2] DEFAULT (0),
    [HANDLING_1] money NOT NULL CONSTRAINT [DF_Orders_HANDLING_1] DEFAULT (0),
    [HANDLING_2] money NOT NULL CONSTRAINT [DF_Orders_HANDLING_2] DEFAULT (0),
    [CANCELLATION_FEE] money NOT NULL CONSTRAINT [DF_Orders_CANCELLATION_FEE] DEFAULT (0),
    [TAX_1] money NOT NULL CONSTRAINT [DF_Orders_TAX_1] DEFAULT (0),
    [TAX_2] money NOT NULL CONSTRAINT [DF_Orders_TAX_2] DEFAULT (0),
    [TAX_3] money NOT NULL CONSTRAINT [DF_Orders_TAX_3] DEFAULT (0),
    [LINE_PAY] money NOT NULL CONSTRAINT [DF_Orders_LINE_PAY] DEFAULT (0),
    [OTHER_PAY] money NOT NULL CONSTRAINT [DF_Orders_OTHER_PAY] DEFAULT (0),
    [AR_PAY] money NOT NULL CONSTRAINT [DF_Orders_AR_PAY] DEFAULT (0),
    [TAX_AUTHOR_1] varchar(15) NOT NULL CONSTRAINT [DF_Orders_TAX_AUTHOR_1] DEFAULT (''),
    [TAX_AUTHOR_2] varchar(15) NOT NULL CONSTRAINT [DF_Orders_TAX_AUTHOR_2] DEFAULT (''),
    [TAX_AUTHOR_3] varchar(15) NOT NULL CONSTRAINT [DF_Orders_TAX_AUTHOR_3] DEFAULT (''),
    [TAX_RATE_1] numeric(15, 4) NOT NULL CONSTRAINT [DF_Orders_TAX_RATE_1] DEFAULT (0),
    [TAX_RATE_2] numeric(15, 4) NOT NULL CONSTRAINT [DF_Orders_TAX_RATE_2] DEFAULT (0),
    [TAX_RATE_3] numeric(15, 4) NOT NULL CONSTRAINT [DF_Orders_TAX_RATE_3] DEFAULT (0),
    [TAX_EXEMPT] varchar(15) NOT NULL CONSTRAINT [DF_Orders_TAX_EXEMPT] DEFAULT (''),
    [TERMS_CODE] varchar(5) NOT NULL CONSTRAINT [DF_Orders_TERMS_CODE] DEFAULT (''),
    [SCHEDULED_DATE] datetime NULL,
    [CONFIRMATION_DATE_TIME] datetime NULL,
    [SHIP_PAPERS_DATE_TIME] datetime NULL,
    [SHIPPED_DATE_TIME] datetime NULL,
    [BO_RELEASED_DATE_TIME] datetime NULL,
    [SOURCE_CODE] varchar(40) NOT NULL CONSTRAINT [DF_Orders_SOURCE_CODE] DEFAULT (''),
    [SALESMAN] varchar(15) NOT NULL CONSTRAINT [DF_Orders_SALESMAN] DEFAULT (''),
    [COMMISSION_RATE] numeric(15, 2) NOT NULL CONSTRAINT [DF_Orders_COMMISSION_RATE] DEFAULT (0),
    [DISCOUNT_RATE] numeric(15, 2) NOT NULL CONSTRAINT [DF_Orders_DISCOUNT_RATE] DEFAULT (0),
    [PRIORITY] int NOT NULL CONSTRAINT [DF_Orders_PRIORITY] DEFAULT (0),
    [HOLD_COMMENT] varchar(255) NOT NULL CONSTRAINT [DF_Orders_HOLD_COMMENT] DEFAULT (''),
    [AFFECT_INVENTORY] bit NOT NULL CONSTRAINT [DF_Orders_AFFECT_INVENTORY] DEFAULT (0),
    [HOLD_FLAG] bit NOT NULL CONSTRAINT [DF_Orders_HOLD_FLAG] DEFAULT (0),
    [CUSTOMER_REFERENCE] varchar(40) NOT NULL CONSTRAINT [DF_Orders_CUSTOMER_REFERENCE] DEFAULT (''),
    [VALUATION_BASIS] tinyint NOT NULL CONSTRAINT [DF_Orders_VALUATION_BASIS] DEFAULT (0),
    [UNDISCOUNTED_TOTAL] money NOT NULL CONSTRAINT [DF_Orders_UNDISCOUNTED_TOTAL] DEFAULT (0),
    [AUTO_CALC_HANDLING] bit NOT NULL CONSTRAINT [DF_Orders_AUTO_CALC_HANDLING] DEFAULT (0),
    [AUTO_CALC_RESTOCKING] bit NOT NULL CONSTRAINT [DF_Orders_AUTO_CALC_RESTOCKING] DEFAULT (0),
    [BACKORDERS] tinyint NOT NULL CONSTRAINT [DF_Orders_BACKORDERS] DEFAULT (0),
    [MEMBER_TYPE] varchar(5) NOT NULL CONSTRAINT [DF_Orders_MEMBER_TYPE] DEFAULT (''),
    [PAY_TYPE] varchar(10) NOT NULL CONSTRAINT [DF_Orders_PAY_TYPE] DEFAULT (''),
    [PAY_NUMBER] varchar(25) NOT NULL CONSTRAINT [DF_Orders_PAY_NUMBER] DEFAULT (''),
    [CREDIT_CARD_EXPIRES] varchar(10) NOT NULL CONSTRAINT [DF_Orders_CREDIT_CARD_EXPIRES] DEFAULT (''),
    [AUTHORIZE] varchar(10) NOT NULL CONSTRAINT [DF_Orders_AUTHORIZE] DEFAULT (''),
    [CREDIT_CARD_NAME] varchar(30) NOT NULL CONSTRAINT [DF_Orders_CREDIT_CARD_NAME] DEFAULT (''),
    [BO_STATUS] tinyint NOT NULL CONSTRAINT [DF_Orders_BO_STATUS] DEFAULT (0),
    [BO_RELEASE_DATE] datetime NULL,
    [TOTAL_QUANTITY_ORDERED] numeric(15, 4) NOT NULL CONSTRAINT [DF_Orders_TOTAL_QUANTITY_ORDERED] DEFAULT (0),
    [TOTAL_QUANTITY_BACKORDERED] numeric(15, 4) NOT NULL CONSTRAINT [DF_Orders_TOTAL_QUANTITY_BACKORDERED] DEFAULT (0),
    [SHIP_METHOD] varchar(10) NOT NULL CONSTRAINT [DF_Orders_SHIP_METHOD] DEFAULT (''),
    [TOTAL_WEIGHT] numeric(15, 2) NOT NULL CONSTRAINT [DF_Orders_TOTAL_WEIGHT] DEFAULT (0),
    [CASH_GL_ACCT] varchar(30) NOT NULL CONSTRAINT [DF_Orders_CASH_GL_ACCT] DEFAULT (''),
    [LINE_PST_TAXABLE] money NOT NULL CONSTRAINT [DF_Orders_LINE_PST_TAXABLE] DEFAULT (0),
    [INTENT_TO_EDIT] varchar(30) NOT NULL CONSTRAINT [DF_Orders_INTENT_TO_EDIT] DEFAULT (''),
    [PREPAID_INVOICE_REFERENCE_NUM] int NOT NULL CONSTRAINT [DF_Orders_PREPAID_INVOICE_REFERENCE_NUM] DEFAULT (0),
    [AUTO_CALC_FREIGHT] bit NOT NULL CONSTRAINT [DF_Orders_AUTO_CALC_FREIGHT] DEFAULT (0),
    [CO_ID] varchar(10) NOT NULL CONSTRAINT [DF_Orders_CO_ID] DEFAULT (''),
    [CO_MEMBER_TYPE] varchar(5) NOT NULL CONSTRAINT [DF_Orders_CO_MEMBER_TYPE] DEFAULT (''),
    [EMAIL] varchar(100) NOT NULL CONSTRAINT [DF_Orders_EMAIL] DEFAULT (''),
    [CRRT] varchar(40) NOT NULL CONSTRAINT [DF_Orders_CRRT] DEFAULT (''),
    [ADDRESS_STATUS] varchar(5) NOT NULL CONSTRAINT [DF_Orders_ADDRESS_STATUS] DEFAULT (''),
    [RECOGNIZED_CASH_AMOUNT] money NOT NULL CONSTRAINT [DF_Orders_RECOGNIZED_CASH_AMOUNT] DEFAULT (0),
    [IS_FR_ORDER] tinyint NOT NULL CONSTRAINT [DF_Orders_IS_FR_ORDER] DEFAULT (0),
    [VAT_TAX_CODE_FH] varchar(31) NULL,
    [ENCRYPT_PAY_NUMBER] varchar(100) NOT NULL CONSTRAINT [DF_Orders_ENCRYPT_PAY_NUMBER] DEFAULT (''),
    [ENCRYPT_CREDIT_CARD_EXPIRES] varchar(100) NOT NULL CONSTRAINT [DF_Orders_ENCRYPT_CREDIT_CARD_EXPIRES] DEFAULT (''),
    [AUTO_FREIGHT_TYPE] tinyint NOT NULL CONSTRAINT [DF_Orders_AUTO_FREIGHT_TYPE] DEFAULT (0),
    [USE_MEMBER_PRICE] bit NOT NULL CONSTRAINT [DF_Orders_USE_MEMBER_PRICE] DEFAULT (0),
    [ST_PRINT_COMPANY] bit NOT NULL CONSTRAINT [DF_Orders_ST_PRINT_COMPANY] DEFAULT (0),
    [ST_PRINT_TITLE] bit NOT NULL CONSTRAINT [DF_Orders_ST_PRINT_TITLE] DEFAULT (0),
    [TOLL_FREE] varchar(25) NOT NULL CONSTRAINT [DF_Orders_TOLL_FREE] DEFAULT (''),
    [MAIL_CODE] varchar(5) NOT NULL CONSTRAINT [DF_Orders_MAIL_CODE] DEFAULT (''),
    [ADDRESS_3] varchar(40) NOT NULL CONSTRAINT [DF_Orders_ADDRESS_3] DEFAULT (''),
    [ENCRYPT_CSC] varchar(100) NOT NULL CONSTRAINT [DF_Orders_ENCRYPT_CSC] DEFAULT (''),
    [ISSUE_DATE] varchar(10) NOT NULL CONSTRAINT [DF_Orders_ISSUE_DATE] DEFAULT (''),
    [ISSUE_NUMBER] varchar(2) NOT NULL CONSTRAINT [DF_Orders_ISSUE_NUMBER] DEFAULT (''),
    [MORE_PAYMENTS] numeric(15, 2) NOT NULL CONSTRAINT [DF_Orders_MORE_PAYMENTS] DEFAULT (0),
    [GATEWAY_REF] varchar(100) NOT NULL CONSTRAINT [DF_Orders_GATEWAY_REF] DEFAULT (''),
    [TIME_STAMP] timestamp,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED ([ORDER_NUMBER] ASC)
)
END

INSERT INTO [dbo].[Orders] ([ORDER_NUMBER],[ORG_CODE],[ORDER_TYPE_CODE],[STAGE],[SOURCE_SYSTEM],[BATCH_NUM],[STATUS],[HOLD_CODE],[ORDER_DATE],
       [BT_ID],[ST_ID],[ST_ADDRESS_NUM],[ENTERED_DATE_TIME],[ENTERED_BY],[UPDATED_DATE_TIME],[UPDATED_BY],[INVOICE_REFERENCE_NUM],
       [INVOICE_NUMBER],[INVOICE_DATE],[NUMBER_LINES],[FULL_NAME],[TITLE],[COMPANY],[FULL_ADDRESS],[PREFIX],[FIRST_NAME],
       [MIDDLE_NAME],[LAST_NAME],[SUFFIX],[DESIGNATION],[INFORMAL],[LAST_FIRST],[COMPANY_SORT],[ADDRESS_1],[ADDRESS_2],[CITY],
       [STATE_PROVINCE],[ZIP],[COUNTRY],[DPB],[BAR_CODE],[ADDRESS_FORMAT],[PHONE],[FAX],[NOTES],[TOTAL_CHARGES],[TOTAL_PAYMENTS],
       [BALANCE],[LINE_TOTAL],[LINE_TAXABLE],[FREIGHT_1],[FREIGHT_2],[HANDLING_1],[HANDLING_2],[CANCELLATION_FEE],[TAX_1],[TAX_2],
       [TAX_3],[LINE_PAY],[OTHER_PAY],[AR_PAY],[TAX_AUTHOR_1],[TAX_AUTHOR_2],[TAX_AUTHOR_3],[TAX_RATE_1],[TAX_RATE_2],[TAX_RATE_3],
       [TAX_EXEMPT],[TERMS_CODE],[SCHEDULED_DATE],[CONFIRMATION_DATE_TIME],[SHIP_PAPERS_DATE_TIME],[SHIPPED_DATE_TIME],
       [BO_RELEASED_DATE_TIME],[SOURCE_CODE],[SALESMAN],[COMMISSION_RATE],[DISCOUNT_RATE],[PRIORITY],[HOLD_COMMENT],
       [AFFECT_INVENTORY],[HOLD_FLAG],[CUSTOMER_REFERENCE],[VALUATION_BASIS],[UNDISCOUNTED_TOTAL],[AUTO_CALC_HANDLING],
       [AUTO_CALC_RESTOCKING],[BACKORDERS],[MEMBER_TYPE],[PAY_TYPE],[PAY_NUMBER],[CREDIT_CARD_EXPIRES],[AUTHORIZE],
       [CREDIT_CARD_NAME],[BO_STATUS],[BO_RELEASE_DATE],[TOTAL_QUANTITY_ORDERED],[TOTAL_QUANTITY_BACKORDERED],[SHIP_METHOD],
       [TOTAL_WEIGHT],[CASH_GL_ACCT],[LINE_PST_TAXABLE],[INTENT_TO_EDIT],[PREPAID_INVOICE_REFERENCE_NUM],[AUTO_CALC_FREIGHT],
       [CO_ID],[CO_MEMBER_TYPE],[EMAIL],[CRRT],[ADDRESS_STATUS],[RECOGNIZED_CASH_AMOUNT],[IS_FR_ORDER],[VAT_TAX_CODE_FH],
       [ENCRYPT_PAY_NUMBER],[ENCRYPT_CREDIT_CARD_EXPIRES],[AUTO_FREIGHT_TYPE],[USE_MEMBER_PRICE],[ST_PRINT_COMPANY],
       [ST_PRINT_TITLE],[TOLL_FREE],[MAIL_CODE],[ADDRESS_3],[ENCRYPT_CSC],[ISSUE_DATE],[ISSUE_NUMBER],[MORE_PAYMENTS],
       [GATEWAY_REF])
SELECT [ORDER_NUMBER],[ORG_CODE],[ORDER_TYPE_CODE],[STAGE],[SOURCE_SYSTEM],[BATCH_NUM],[STATUS],[HOLD_CODE],[ORDER_DATE],
       [BT_ID],[ST_ID],[ST_ADDRESS_NUM],[ENTERED_DATE_TIME],[ENTERED_BY],[UPDATED_DATE_TIME],[UPDATED_BY],[INVOICE_REFERENCE_NUM],
       [INVOICE_NUMBER],[INVOICE_DATE],[NUMBER_LINES],[FULL_NAME],[TITLE],[COMPANY],[FULL_ADDRESS],[PREFIX],[FIRST_NAME],
       [MIDDLE_NAME],[LAST_NAME],[SUFFIX],[DESIGNATION],[INFORMAL],[LAST_FIRST],[COMPANY_SORT],[ADDRESS_1],[ADDRESS_2],[CITY],
       [STATE_PROVINCE],[ZIP],[COUNTRY],[DPB],[BAR_CODE],[ADDRESS_FORMAT],[PHONE],[FAX],[NOTES],[TOTAL_CHARGES],[TOTAL_PAYMENTS],
       [BALANCE],[LINE_TOTAL],[LINE_TAXABLE],[FREIGHT_1],[FREIGHT_2],[HANDLING_1],[HANDLING_2],[CANCELLATION_FEE],[TAX_1],[TAX_2],
       [TAX_3],[LINE_PAY],[OTHER_PAY],[AR_PAY],[TAX_AUTHOR_1],[TAX_AUTHOR_2],[TAX_AUTHOR_3],[TAX_RATE_1],[TAX_RATE_2],[TAX_RATE_3],
       [TAX_EXEMPT],[TERMS_CODE],[SCHEDULED_DATE],[CONFIRMATION_DATE_TIME],[SHIP_PAPERS_DATE_TIME],[SHIPPED_DATE_TIME],
       [BO_RELEASED_DATE_TIME],[SOURCE_CODE],[SALESMAN],[COMMISSION_RATE],[DISCOUNT_RATE],[PRIORITY],[HOLD_COMMENT],
       [AFFECT_INVENTORY],[HOLD_FLAG],[CUSTOMER_REFERENCE],[VALUATION_BASIS],[UNDISCOUNTED_TOTAL],[AUTO_CALC_HANDLING],
       [AUTO_CALC_RESTOCKING],[BACKORDERS],[MEMBER_TYPE],[PAY_TYPE],[PAY_NUMBER],[CREDIT_CARD_EXPIRES],[AUTHORIZE],
       [CREDIT_CARD_NAME],[BO_STATUS],[BO_RELEASE_DATE],[TOTAL_QUANTITY_ORDERED],[TOTAL_QUANTITY_BACKORDERED],[SHIP_METHOD],
       [TOTAL_WEIGHT],[CASH_GL_ACCT],[LINE_PST_TAXABLE],[INTENT_TO_EDIT],[PREPAID_INVOICE_REFERENCE_NUM],[AUTO_CALC_FREIGHT],
       [CO_ID],[CO_MEMBER_TYPE],[EMAIL],[CRRT],[ADDRESS_STATUS],[RECOGNIZED_CASH_AMOUNT],[IS_FR_ORDER],[VAT_TAX_CODE_FH],
       [ENCRYPT_PAY_NUMBER],[ENCRYPT_CREDIT_CARD_EXPIRES],[AUTO_FREIGHT_TYPE],[USE_MEMBER_PRICE],[ST_PRINT_COMPANY],
       [ST_PRINT_TITLE],[TOLL_FREE],[MAIL_CODE],[ADDRESS_3],[ENCRYPT_CSC],[ISSUE_DATE],[ISSUE_NUMBER],[MORE_PAYMENTS],
       [GATEWAY_REF]
  FROM [dbo].[Orders_BAK]

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') AND [name] = N'iOrdersBT_ID')
BEGIN
    CREATE NONCLUSTERED INDEX [iOrdersBT_ID] ON [dbo].[Orders] ([BT_ID] ASC)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') AND [name] = N'iOrdersCO_ID')
BEGIN
    CREATE NONCLUSTERED INDEX [iOrdersCO_ID] ON [dbo].[Orders] ([CO_ID] ASC)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') AND [name] = N'iOrdersCOMPANY_SORT')
BEGIN
    CREATE NONCLUSTERED INDEX [iOrdersCOMPANY_SORT] ON [dbo].[Orders] ([COMPANY_SORT] ASC)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') AND [name] = N'iOrdersINVOICE_REF_NUM')
BEGIN
    CREATE NONCLUSTERED INDEX [iOrdersINVOICE_REF_NUM] ON [dbo].[Orders] ([INVOICE_REFERENCE_NUM] ASC)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') AND [name] = N'iOrdersIS_FR_ORDER')
BEGIN
    CREATE NONCLUSTERED INDEX [iOrdersIS_FR_ORDER] ON [dbo].[Orders] ([IS_FR_ORDER] ASC)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') AND [name] = N'iOrdersLAST_FIRST')
BEGIN
    CREATE NONCLUSTERED INDEX [iOrdersLAST_FIRST] ON [dbo].[Orders] ([LAST_FIRST] ASC)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') AND [name] = N'iOrdersST_ID')
BEGIN
    CREATE NONCLUSTERED INDEX [iOrdersST_ID] ON [dbo].[Orders] ([ST_ID] ASC)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') AND [name] = N'iOrdersSTAGE')
BEGIN
    CREATE NONCLUSTERED INDEX [iOrdersSTAGE] ON [dbo].[Orders] ([STAGE] ASC)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Orders]') AND [name] = N'iOrdersSTATUS')
BEGIN
    CREATE NONCLUSTERED INDEX [iOrdersSTATUS] ON [dbo].[Orders] ([STATUS] ASC)
END

IF EXISTS (SELECT 1 FROM sysobjects WHERE type = 'U ' and name = 'Orders')
    GRANT INSERT, UPDATE, DELETE, SELECT, REFERENCES ON [dbo].[Orders] TO [IMIS] AS [dbo]

DROP TABLE [dbo].[Orders_BAK]

COMMIT
GO

----------------------------------------------

BEGIN TRANSACTION

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Order_Meet')
BEGIN
    IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Order_Meet_BAK')
    BEGIN
        DROP TABLE [dbo].[Order_Meet_BAK]
    END
    EXEC dbo.asi_RenameTable 'Order_Meet', 'Order_Meet_BAK'
END

SET ANSI_DEFAULTS ON
SET IMPLICIT_TRANSACTIONS OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM [dbo].[sysobjects] WHERE [id] = OBJECT_ID(N'[dbo].[Order_Meet]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[Order_Meet] (
    [ORDER_NUMBER] numeric(15,2) NOT NULL CONSTRAINT [DF_Order_Meet_ORDER_NUMBER] DEFAULT (0),
    [MEETING] varchar(10) NOT NULL CONSTRAINT [DF_Order_Meet_MEETING] DEFAULT (''),
    [REGISTRANT_CLASS] varchar(5) NOT NULL CONSTRAINT [DF_Order_Meet_REGISTRANT_CLASS] DEFAULT (''),
    [ARRIVAL] datetime NULL,
    [DEPARTURE] datetime NULL,
    [HOTEL] varchar(40) NOT NULL CONSTRAINT [DF_Order_Meet_HOTEL] DEFAULT (''),
    [LODGING_INSTRUCTIONS] varchar(255) NOT NULL CONSTRAINT [DF_Order_Meet_LODGING_INSTRUCTIONS] DEFAULT (''),
    [BOOTH] varchar(255) NOT NULL CONSTRAINT [DF_Order_Meet_BOOTH] DEFAULT (''),
    [GUEST_FIRST] varchar(20) NOT NULL CONSTRAINT [DF_Order_Meet_GUEST_FIRST] DEFAULT (''),
    [GUEST_MIDDLE] varchar(20) NOT NULL CONSTRAINT [DF_Order_Meet_GUEST_MIDDLE] DEFAULT (''),
    [GUEST_LAST] varchar(30) NOT NULL CONSTRAINT [DF_Order_Meet_GUEST_LAST] DEFAULT (''),
    [GUEST_IS_SPOUSE] bit NOT NULL CONSTRAINT [DF_Order_Meet_GUEST_IS_SPOUSE] DEFAULT (0),
    [ADDITIONAL_BADGES] text NULL,
    [DELEGATE] varchar(10) NOT NULL CONSTRAINT [DF_Order_Meet_DELEGATE] DEFAULT (''),
    [UF_1] bit NOT NULL CONSTRAINT [DF_Order_Meet_UF_1] DEFAULT (0),
    [UF_2] bit NOT NULL CONSTRAINT [DF_Order_Meet_UF_2] DEFAULT (0),
    [UF_3] bit NOT NULL CONSTRAINT [DF_Order_Meet_UF_3] DEFAULT (0),
    [UF_4] bit NOT NULL CONSTRAINT [DF_Order_Meet_UF_4] DEFAULT (0),
    [UF_5] bit NOT NULL CONSTRAINT [DF_Order_Meet_UF_5] DEFAULT (0),
    [UF_6] varchar(100) NOT NULL CONSTRAINT [DF_Order_Meet_UF_6] DEFAULT (''),
    [UF_7] varchar(100) NOT NULL CONSTRAINT [DF_Order_Meet_UF_7] DEFAULT (''),
    [UF_8] varchar(100) NOT NULL CONSTRAINT [DF_Order_Meet_UF_8] DEFAULT (''),
    [SHARE_STATUS] int NOT NULL CONSTRAINT [DF_Order_Meet_SHARE_STATUS] DEFAULT (0),
    [SHARE_ORDER_NUMBER] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Meet_SHARE_ORDER_NUMBER] DEFAULT (0),
    [ROOM_TYPE] varchar(8) NOT NULL CONSTRAINT [DF_Order_Meet_ROOM_TYPE] DEFAULT (''),
    [ROOM_QUANTITY] int NOT NULL CONSTRAINT [DF_Order_Meet_ROOM_QUANTITY] DEFAULT (0),
    [ROOM_CONFIRM] bit NOT NULL CONSTRAINT [DF_Order_Meet_ROOM_CONFIRM] DEFAULT (0),
    [UF_9] text NULL,
    [UF_10] text NULL,
    [ARRIVAL_TIME] datetime NULL,
    [DEPARTURE_TIME] datetime NULL,
    [COMP_REGISTRATIONS] int NOT NULL CONSTRAINT [DF_Order_Meet_COMP_REGISTRATIONS] DEFAULT (0),
    [COMP_REG_SOURCE] DECIMAL(15,6) NULL,
    [TOTAL_SQUARE_FEET] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Meet_TOTAL_SQUARE_FEET] DEFAULT (0),
    [COMP_REGISTRATIONS_USED] int NOT NULL CONSTRAINT [DF_Order_Meet_COMP_REGISTRATIONS_USED] DEFAULT (0),
    [TIME_STAMP] timestamp NULL
)
END

 INSERT INTO Order_Meet ([ORDER_NUMBER], [MEETING], [REGISTRANT_CLASS], [ARRIVAL], [DEPARTURE], [HOTEL], [LODGING_INSTRUCTIONS], 
                         [BOOTH], [GUEST_FIRST], [GUEST_MIDDLE], [GUEST_LAST], [GUEST_IS_SPOUSE], [ADDITIONAL_BADGES], [DELEGATE], 
                         [UF_1], [UF_2], [UF_3], [UF_4], [UF_5], [UF_6], [UF_7], [UF_8], [SHARE_STATUS], [SHARE_ORDER_NUMBER], 
                         [ROOM_TYPE], [ROOM_QUANTITY], [ROOM_CONFIRM], [UF_9], [UF_10], [ARRIVAL_TIME], [DEPARTURE_TIME], 
                         [COMP_REGISTRATIONS], [COMP_REG_SOURCE], [TOTAL_SQUARE_FEET], [COMP_REGISTRATIONS_USED])
      SELECT ISNULL([ORDER_NUMBER], 0), ISNULL([MEETING], ''), ISNULL([REGISTRANT_CLASS], ''), [ARRIVAL], [DEPARTURE], ISNULL([HOTEL], ''), 
             ISNULL([LODGING_INSTRUCTIONS], ''), ISNULL([BOOTH], ''), ISNULL([GUEST_FIRST], ''), ISNULL([GUEST_MIDDLE], ''), ISNULL([GUEST_LAST], ''), 
             ISNULL([GUEST_IS_SPOUSE], 0), [ADDITIONAL_BADGES], ISNULL([DELEGATE], ''), ISNULL([UF_1], 0), ISNULL([UF_2], 0), ISNULL([UF_3], 0), 
             ISNULL([UF_4], 0), ISNULL([UF_5], 0), ISNULL([UF_6], ''), ISNULL([UF_7], ''), ISNULL([UF_8], ''), ISNULL([SHARE_STATUS], 0), 
             ISNULL([SHARE_ORDER_NUMBER], 0), ISNULL([ROOM_TYPE], ''), ISNULL([ROOM_QUANTITY], 0), ISNULL([ROOM_CONFIRM], 0), [UF_9], [UF_10], 
             [ARRIVAL_TIME], [DEPARTURE_TIME], ISNULL([COMP_REGISTRATIONS], 0), [COMP_REG_SOURCE], ISNULL([TOTAL_SQUARE_FEET], 0), 
             ISNULL([COMP_REGISTRATIONS_USED], 0)
        FROM Order_Meet_BAK


IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Order_Meet]') AND [name] = N'PK_Order_Meet')
BEGIN
  ALTER TABLE [dbo].[Order_Meet]
  ADD CONSTRAINT PK_Order_Meet PRIMARY KEY NONCLUSTERED (ORDER_NUMBER)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Order_Meet]') AND [name] = N'iOrder_MeetREGISTRANT_CLASS')
BEGIN
  CREATE NONCLUSTERED INDEX iOrder_MeetREGISTRANT_CLASS ON [dbo].[Order_Meet] (REGISTRANT_CLASS)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Order_Meet]') AND [name] = N'iOrder_MeetMEETING')
BEGIN
  CREATE CLUSTERED INDEX iOrder_MeetMEETING ON [dbo].[Order_Meet] (MEETING)
END

IF EXISTS (SELECT 1 FROM sysobjects WHERE type = 'U ' and name = 'Order_Meet')
    GRANT REFERENCES, SELECT, INSERT, DELETE, UPDATE ON Order_Meet TO IMIS

DROP TABLE [dbo].[Order_Meet_BAK]

COMMIT
GO

----------------------------------------------

BEGIN TRANSACTION

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Order_Lines')
BEGIN
    IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Order_Lines_BAK')
    BEGIN
        DROP TABLE [dbo].[Order_Meet_BAK]
    END
    EXEC dbo.asi_RenameTable 'Order_Lines', 'Order_Lines_BAK'
END

SET ANSI_DEFAULTS ON
SET IMPLICIT_TRANSACTIONS OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM [dbo].[sysobjects] WHERE [id] = OBJECT_ID(N'[dbo].[Order_Lines]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[Order_Lines] (
    [ORDER_NUMBER] numeric(15,2) NOT NULL CONSTRAINT [DF_Order_Lines_ORDER_NUMBER] DEFAULT (0),
    [LINE_NUMBER] numeric(15,2) NOT NULL CONSTRAINT [DF_Order_Lines_LINE_NUMBER] DEFAULT (0),
    [PRODUCT_CODE] varchar(31) NOT NULL CONSTRAINT [DF_Order_Lines_PRODUCT_CODE] DEFAULT (''),
    [LOCATION] varchar(10) NOT NULL CONSTRAINT [DF_Order_Lines_LOCATION] DEFAULT (''),
    [LOT_SERIAL] varchar(20) NOT NULL CONSTRAINT [DF_Order_Lines_LOT_SERIAL] DEFAULT (''),
    [DESCRIPTION] varchar(255) NOT NULL CONSTRAINT [DF_Order_Lines_DESCRIPTION] DEFAULT (''),
    [QUANTITY_ORDERED] numeric(15,6) NOT NULL CONSTRAINT [DF_Order_Lines_QUANTITY_ORDERED] DEFAULT (0),
    [QUANTITY_SHIPPED] numeric(15,6) NOT NULL CONSTRAINT [DF_Order_Lines_QUANTITY_SHIPPED] DEFAULT (0),
    [QUANTITY_BACKORDERED] numeric(15,6) NOT NULL CONSTRAINT [DF_Order_Lines_QUANTITY_BACKORDERED] DEFAULT (0),
    [QUANTITY_RESERVED] numeric(15,6) NOT NULL CONSTRAINT [DF_Order_Lines_QUANTITY_RESERVED] DEFAULT (0),
    [QUANTITY_COMMITTED] numeric(15,6) NOT NULL CONSTRAINT [DF_Order_Lines_QUANTITY_COMMITTED] DEFAULT (0),
    [NUMBER_DAYS] int NOT NULL CONSTRAINT [DF_Order_Lines_NUMBER_DAYS] DEFAULT (0),
    [TAXABLE] bit NOT NULL CONSTRAINT [DF_Order_Lines_TAXABLE] DEFAULT (0),
    [TAXABLE_2] bit NOT NULL CONSTRAINT [DF_Order_Lines_TAXABLE_2] DEFAULT (0),
    [UNIT_PRICE] money NOT NULL CONSTRAINT [DF_Order_Lines_UNIT_PRICE] DEFAULT (0),
    [UNIT_COST] money NOT NULL CONSTRAINT [DF_Order_Lines_UNIT_COST] DEFAULT (0),
    [UNDISCOUNTED_PRICE] money NOT NULL CONSTRAINT [DF_Order_Lines_UNDISCOUNTED_PRICE] DEFAULT (0),
    [EXTENDED_AMOUNT] money NOT NULL CONSTRAINT [DF_Order_Lines_EXTENDED_AMOUNT] DEFAULT (0),
    [EXTENDED_COST] money NOT NULL CONSTRAINT [DF_Order_Lines_EXTENDED_COST] DEFAULT (0),
    [UNDISCOUNTED_EXTENDED_AMOUNT] money NOT NULL CONSTRAINT [DF_Order_Lines_UNDISCOUNTED_EXTENDED_AMOUNT] DEFAULT (0),
    [CANCEL_CODE] varchar(10) NOT NULL CONSTRAINT [DF_Order_Lines_CANCEL_CODE] DEFAULT (''),
    [CANCEL_QUANTITY] numeric(15,6) NOT NULL CONSTRAINT [DF_Order_Lines_CANCEL_QUANTITY] DEFAULT (0),
    [COMMISSION_RATE] numeric(15, 4) NOT NULL CONSTRAINT [DF_Order_Lines_COMMISSION_RATE] DEFAULT (0),
    [COMMISSION_AMOUNT] money NOT NULL CONSTRAINT [DF_Order_Lines_COMMISSION_AMOUNT] DEFAULT (0),
    [CEU_TYPE] varchar(15) NOT NULL CONSTRAINT [DF_Order_Lines_CEU_TYPE] DEFAULT (''),
    [CEU_AWARDED] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Lines_CEU_AWARDED] DEFAULT (0),
    [PASS_FAIL] varchar(5) NOT NULL CONSTRAINT [DF_Order_Lines_PASS_FAIL] DEFAULT (''),
    [DATE_CONFIRMED] datetime NULL,
    [TICKETS_PRINTED] int NOT NULL CONSTRAINT [DF_Order_Lines_TICKETS_PRINTED] DEFAULT (0),
    [BOOTH_NUMBERS] varchar(255) NOT NULL CONSTRAINT [DF_Order_Lines_BOOTH_NUMBERS] DEFAULT (''),
    [NOTE] varchar(255) NULL,
    [INCOME_ACCOUNT] varchar(50) NOT NULL CONSTRAINT [DF_Order_Lines_INCOME_ACCOUNT] DEFAULT (''),
    [UNIT_WEIGHT] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Lines_UNIT_WEIGHT] DEFAULT (0),
    [EXTENDED_WEIGHT] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Lines_EXTENDED_WEIGHT] DEFAULT (0),
    [PST_TAXABLE] bit NOT NULL CONSTRAINT [DF_Order_Lines_PST_TAXABLE] DEFAULT (0),
    [IS_GST_TAXABLE] bit NOT NULL CONSTRAINT [DF_Order_Lines_IS_GST_TAXABLE] DEFAULT (0),
    [ADDED_TO_WAIT_LIST] datetime NULL,
    [BIN] varchar(10) NOT NULL CONSTRAINT [DF_Order_Lines_BIN] DEFAULT (''),
    [TAX_AUTHORITY] varchar(15) NOT NULL CONSTRAINT [DF_Order_Lines_TAX_AUTHORITY] DEFAULT (''),
    [TAX_RATE] numeric(15, 4) NOT NULL CONSTRAINT [DF_Order_Lines_TAX_RATE] DEFAULT (0),
    [TAX_1] numeric(15, 4) NOT NULL CONSTRAINT [DF_Order_Lines_TAX_1] DEFAULT (0),
    [KIT_ITEM_TYPE] tinyint NOT NULL CONSTRAINT [DF_Order_Lines_KIT_ITEM_TYPE] DEFAULT (0),
    [DISCOUNT] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Lines_DISCOUNT] DEFAULT (0),
    [UF_1] varchar(30) NOT NULL CONSTRAINT [DF_Order_Lines_UF_1] DEFAULT (''),
    [UF_2] varchar(30) NOT NULL CONSTRAINT [DF_Order_Lines_UF_2] DEFAULT (''),
    [UF_3] varchar(30) NOT NULL CONSTRAINT [DF_Order_Lines_UF_3] DEFAULT (''),
    [UF_4] varchar(30) NOT NULL CONSTRAINT [DF_Order_Lines_UF_4] DEFAULT (''),
    [EXTENDED_SQUARE_FEET] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Lines_EXTENDED_SQUARE_FEET] DEFAULT (0),
    [SQUARE_FEET] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Lines_SQUARE_FEET] DEFAULT (0),
    [MEET_APPEAL] varchar(40) NOT NULL CONSTRAINT [DF_Order_Lines_MEET_APPEAL] DEFAULT (''),
    [MEET_CAMPAIGN] varchar(10) NOT NULL CONSTRAINT [DF_Order_Lines_MEET_CAMPAIGN] DEFAULT (''),
    [FAIR_MARKET_VALUE] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Lines_FAIR_MARKET_VALUE] DEFAULT (0),
    [ORG_CODE] varchar(5) NOT NULL CONSTRAINT [DF_Order_Lines_ORG_CODE] DEFAULT (''),
    [IS_FR_ITEM] bit NOT NULL CONSTRAINT [DF_Order_Lines_IS_FR_ITEM] DEFAULT (0),
    [MANUAL_PRICE] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Lines_MANUAL_PRICE] DEFAULT (0),
    [IS_MANUAL_PRICE] bit NOT NULL CONSTRAINT [DF_Order_Lines_IS_MANUAL_PRICE] DEFAULT (0),
    [TIME_STAMP] timestamp NULL
)

END

INSERT INTO Order_Lines ([ORDER_NUMBER], [LINE_NUMBER], [PRODUCT_CODE], [LOCATION], [LOT_SERIAL], [DESCRIPTION], [QUANTITY_ORDERED], 
                         [QUANTITY_SHIPPED], [QUANTITY_BACKORDERED], [QUANTITY_RESERVED], [QUANTITY_COMMITTED], [NUMBER_DAYS], 
                         [TAXABLE], [TAXABLE_2], [UNIT_PRICE], [UNIT_COST], [UNDISCOUNTED_PRICE], [EXTENDED_AMOUNT], [EXTENDED_COST], 
                         [UNDISCOUNTED_EXTENDED_AMOUNT], [CANCEL_CODE], [CANCEL_QUANTITY], [COMMISSION_RATE], [COMMISSION_AMOUNT], 
                         [CEU_TYPE], [CEU_AWARDED], [PASS_FAIL], [DATE_CONFIRMED], [TICKETS_PRINTED], [BOOTH_NUMBERS], [NOTE], 
                         [INCOME_ACCOUNT], [UNIT_WEIGHT], [EXTENDED_WEIGHT], [PST_TAXABLE], [IS_GST_TAXABLE], [ADDED_TO_WAIT_LIST], 
                         [BIN], [TAX_AUTHORITY], [TAX_RATE], [TAX_1], [KIT_ITEM_TYPE], [DISCOUNT], [UF_1], [UF_2], [UF_3], [UF_4], 
                         [EXTENDED_SQUARE_FEET], [SQUARE_FEET], [MEET_APPEAL], [MEET_CAMPAIGN], [FAIR_MARKET_VALUE], [ORG_CODE], 
                         [IS_FR_ITEM], [MANUAL_PRICE], [IS_MANUAL_PRICE])
      SELECT ISNULL([ORDER_NUMBER], 0), ISNULL([LINE_NUMBER], 0), ISNULL([PRODUCT_CODE], ''), ISNULL([LOCATION], ''), ISNULL([LOT_SERIAL], ''), 
             ISNULL([DESCRIPTION], ''), ISNULL([QUANTITY_ORDERED], 0), ISNULL([QUANTITY_SHIPPED], 0), ISNULL([QUANTITY_BACKORDERED], 0), 
             ISNULL([QUANTITY_RESERVED], 0), ISNULL([QUANTITY_COMMITTED], 0), ISNULL([NUMBER_DAYS], 0), ISNULL([TAXABLE], 0), 
             ISNULL([TAXABLE_2], 0), ISNULL([UNIT_PRICE], 0), ISNULL([UNIT_COST], 0), ISNULL([UNDISCOUNTED_PRICE], 0), 
             ISNULL([EXTENDED_AMOUNT], 0), ISNULL([EXTENDED_COST], 0), ISNULL([UNDISCOUNTED_EXTENDED_AMOUNT], 0), ISNULL([CANCEL_CODE], ''), 
             ISNULL([CANCEL_QUANTITY], 0), ISNULL([COMMISSION_RATE], 0), ISNULL([COMMISSION_AMOUNT], 0), ISNULL([CEU_TYPE], ''), 
             ISNULL([CEU_AWARDED], 0), ISNULL([PASS_FAIL], ''), [DATE_CONFIRMED], ISNULL([TICKETS_PRINTED], 0), ISNULL([BOOTH_NUMBERS], ''), 
             [NOTE], ISNULL([INCOME_ACCOUNT], ''), ISNULL([UNIT_WEIGHT], 0), ISNULL([EXTENDED_WEIGHT], 0), ISNULL([PST_TAXABLE], 0), 
             ISNULL([IS_GST_TAXABLE], 0), [ADDED_TO_WAIT_LIST], ISNULL([BIN], ''), ISNULL([TAX_AUTHORITY], ''), ISNULL([TAX_RATE], 0), 
             ISNULL([TAX_1], 0), ISNULL([KIT_ITEM_TYPE], 0), ISNULL([DISCOUNT], 0), ISNULL([UF_1], ''), ISNULL([UF_2], ''), ISNULL([UF_3], ''), 
             ISNULL([UF_4], ''), ISNULL([EXTENDED_SQUARE_FEET], 0), ISNULL([SQUARE_FEET], 0), ISNULL([MEET_APPEAL], ''), 
             ISNULL([MEET_CAMPAIGN], ''), ISNULL([FAIR_MARKET_VALUE], 0), ISNULL([ORG_CODE], ''), ISNULL([IS_FR_ITEM], 0), 
             ISNULL([MANUAL_PRICE], 0), ISNULL([IS_MANUAL_PRICE], 0)
        FROM Order_Lines_BAK

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Order_Lines]') AND [name] = N'PK_Order_Lines')
BEGIN
  ALTER TABLE [dbo].[Order_Lines]
  ADD CONSTRAINT PK_Order_Lines PRIMARY KEY CLUSTERED (ORDER_NUMBER, LINE_NUMBER)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Order_Lines]') AND [name] = N'iOrder_LinesPRODUCT_CODE')
BEGIN
  CREATE NONCLUSTERED INDEX iOrder_LinesPRODUCT_CODE ON [dbo].[Order_Lines] (PRODUCT_CODE, LOCATION, LOT_SERIAL)
END

IF EXISTS (SELECT 1 FROM sysobjects WHERE type = 'U ' and name = 'Order_Lines')
    GRANT REFERENCES, SELECT, INSERT, DELETE, UPDATE ON Order_Meet TO IMIS

DROP TABLE [dbo].[Order_Lines_BAK]

COMMIT
GO

----------------------------------------------

BEGIN TRANSACTION

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Order_Payments')
BEGIN
    IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Order_Payments_BAK')
    BEGIN
        DROP TABLE [dbo].[Order_Meet_BAK]
    END
    EXEC dbo.asi_RenameTable 'Order_Payments', 'Order_Payments_BAK'
END

SET ANSI_DEFAULTS ON
SET IMPLICIT_TRANSACTIONS OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM [dbo].[sysobjects] WHERE [id] = OBJECT_ID(N'[dbo].[Order_Payments]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[Order_Payments] (
    [ORDER_NUMBER] numeric(15,2) NOT NULL CONSTRAINT [DF_Order_Payments_ORDER_NUMBER] DEFAULT (0),
    [PAYMENT_NUMBER] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Payments_PAYMENT_NUMBER] DEFAULT (0),
    [ENCRYPT_PAY_NUMBER] varchar(100) NOT NULL CONSTRAINT [DF_Order_Payments_ENCRYPT_PAY_NUMBER] DEFAULT (''),
    [PAY_TYPE] varchar(10) NOT NULL CONSTRAINT [DF_Order_Payments_PAY_TYPE] DEFAULT (''),
    [PAY_NUMBER] varchar(25) NOT NULL CONSTRAINT [DF_Order_Payments_PAY_NUMBER] DEFAULT (''),
    [CREDIT_CARD_EXPIRES] varchar(10) NOT NULL CONSTRAINT [DF_Order_Payments_CREDIT_CARD_EXPIRES] DEFAULT (''),
    [AUTHORIZE] varchar(10) NOT NULL CONSTRAINT [DF_Order_Payments_AUTHORIZE] DEFAULT (''),
    [CREDIT_CARD_NAME] varchar(30) NOT NULL CONSTRAINT [DF_Order_Payments_CREDIT_CARD_NAME] DEFAULT (''),
    [PAY_AMOUNT] numeric(15, 2) NOT NULL CONSTRAINT [DF_Order_Payments_PAY_AMOUNT] DEFAULT (0),
    [CASH_GL_ACCT] varchar(30) NOT NULL CONSTRAINT [DF_Order_Payments_CASH_GL_ACCT] DEFAULT (''),
    [ENCRYPT_CREDIT_CARD_EXPIRES] varchar(100) NOT NULL CONSTRAINT [DF_Order_Payments_ENCRYPT_CREDIT_CARD_EXPIRES] DEFAULT (''),
    [ENCRYPT_CSC] varchar(100) NOT NULL CONSTRAINT [DF_Order_Payments_ENCRYPT_CSC] DEFAULT (''),
    [ISSUE_DATE] varchar(10) NOT NULL CONSTRAINT [DF_Order_Payments_ISSUE_DATE] DEFAULT (''),
    [ISSUE_NUMBER] varchar(2) NOT NULL CONSTRAINT [DF_Order_Payments_ISSUE_NUMBER] DEFAULT (''),
    [TIME_STAMP] timestamp NULL
)

END

 INSERT INTO Order_Payments ([ORDER_NUMBER], [PAYMENT_NUMBER], [ENCRYPT_PAY_NUMBER], [PAY_TYPE], [PAY_NUMBER], [CREDIT_CARD_EXPIRES], 
                             [AUTHORIZE], [CREDIT_CARD_NAME], [PAY_AMOUNT], [CASH_GL_ACCT], [ENCRYPT_CREDIT_CARD_EXPIRES], 
                             [ENCRYPT_CSC], [ISSUE_DATE], [ISSUE_NUMBER])
      SELECT ISNULL([ORDER_NUMBER], 0), ISNULL([PAYMENT_NUMBER], 0), ISNULL([ENCRYPT_PAY_NUMBER], ''), ISNULL([PAY_TYPE], ''), 
             ISNULL([PAY_NUMBER], ''), ISNULL([CREDIT_CARD_EXPIRES], ''), ISNULL([AUTHORIZE], ''), ISNULL([CREDIT_CARD_NAME], ''), 
             ISNULL([PAY_AMOUNT], 0), ISNULL([CASH_GL_ACCT], ''), ISNULL([ENCRYPT_CREDIT_CARD_EXPIRES], ''), ISNULL([ENCRYPT_CSC], ''), 
             ISNULL([ISSUE_DATE], ''), ISNULL([ISSUE_NUMBER], '')
        FROM Order_Payments_BAK


IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Order_Payments]') AND [name] = N'PK_Order_Payments')
BEGIN
  ALTER TABLE [dbo].[Order_Payments]
  ADD CONSTRAINT PK_Order_Payments PRIMARY KEY CLUSTERED (ORDER_NUMBER, PAYMENT_NUMBER)
END

IF EXISTS (SELECT 1 FROM sysobjects WHERE type = 'U ' and name = 'Order_Payments')
    GRANT REFERENCES, SELECT, INSERT, DELETE, UPDATE ON Order_Payments TO IMIS

DROP TABLE [dbo].[Order_Payments_BAK]

COMMIT
GO

----------------------------------------------

BEGIN TRANSACTION

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Order_Badge')
BEGIN
    IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Order_Badge_BAK')
    BEGIN
        DROP TABLE [dbo].[Order_Meet_BAK]
    END
    EXEC dbo.asi_RenameTable 'Order_Badge', 'Order_Badge_BAK'
END

SET ANSI_DEFAULTS ON
SET IMPLICIT_TRANSACTIONS OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM [dbo].[sysobjects] WHERE [id] = OBJECT_ID(N'[dbo].[Order_Badge]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[Order_Badge] (
    [ORDER_NUMBER] numeric(15,2) NOT NULL CONSTRAINT [DF_Order_Badge_ORDER_NUMBER] DEFAULT (0),
    [BADGE_NUMBER] int NOT NULL CONSTRAINT [DF_Order_Badge_BADGE_NUMBER] DEFAULT (0),
    [BADGE_TYPE] varchar(10) NOT NULL CONSTRAINT [DF_Order_Badge_BADGE_TYPE] DEFAULT (''),
    [FULL_NAME] varchar(70) NOT NULL CONSTRAINT [DF_Order_Badge_FULL_NAME] DEFAULT (''),
    [TITLE] varchar(80) NOT NULL CONSTRAINT [DF_Order_Badge_TITLE] DEFAULT (''),
    [COMPANY] varchar(80) NOT NULL CONSTRAINT [DF_Order_Badge_COMPANY] DEFAULT (''),
    [FULL_ADDRESS] varchar(255) NOT NULL CONSTRAINT [DF_Order_Badge_FULL_ADDRESS] DEFAULT (''),
    [PREFIX] varchar(25) NOT NULL CONSTRAINT [DF_Order_Badge_PREFIX] DEFAULT (''),
    [FIRST_NAME] varchar(20) NOT NULL CONSTRAINT [DF_Order_Badge_FIRST_NAME] DEFAULT (''),
    [MIDDLE_NAME] varchar(20) NOT NULL CONSTRAINT [DF_Order_Badge_MIDDLE_NAME] DEFAULT (''),
    [LAST_NAME] varchar(30) NOT NULL CONSTRAINT [DF_Order_Badge_LAST_NAME] DEFAULT (''),
    [SUFFIX] varchar(10) NOT NULL CONSTRAINT [DF_Order_Badge_SUFFIX] DEFAULT (''),
    [DESIGNATION] varchar(20) NOT NULL CONSTRAINT [DF_Order_Badge_DESIGNATION] DEFAULT (''),
    [INFORMAL] varchar(20) NOT NULL CONSTRAINT [DF_Order_Badge_INFORMAL] DEFAULT (''),
    [ADDRESS_1] varchar(40) NOT NULL CONSTRAINT [DF_Order_Badge_ADDRESS_1] DEFAULT (''),
    [ADDRESS_2] varchar(40) NOT NULL CONSTRAINT [DF_Order_Badge_ADDRESS_2] DEFAULT (''),
    [CITY] varchar(40) NOT NULL CONSTRAINT [DF_Order_Badge_CITY] DEFAULT (''),
    [STATE_PROVINCE] varchar(15) NOT NULL CONSTRAINT [DF_Order_Badge_STATE_PROVINCE] DEFAULT (''),
    [ZIP] varchar(10) NOT NULL CONSTRAINT [DF_Order_Badge_ZIP] DEFAULT (''),
    [COUNTRY] varchar(25) NOT NULL CONSTRAINT [DF_Order_Badge_COUNTRY] DEFAULT (''),
    [BAR_CODE] varchar(14) NOT NULL CONSTRAINT [DF_Order_Badge_BAR_CODE] DEFAULT (''),
    [DELEGATE] varchar(10) NULL,
    [ST_PRINT_COMPANY] bit NOT NULL CONSTRAINT [DF_Order_Badge_ST_PRINT_COMPANY] DEFAULT (0),
    [ST_PRINT_TITLE] bit NOT NULL CONSTRAINT [DF_Order_Badge_ST_PRINT_TITLE] DEFAULT (0),
    [ADDRESS_3] varchar(40) NOT NULL CONSTRAINT [DF_Order_Badge_ADDRESS_3] DEFAULT (''),
    [TIME_STAMP] timestamp NULL
)

END

INSERT INTO Order_Badge ([ORDER_NUMBER], [BADGE_NUMBER], [BADGE_TYPE], [FULL_NAME], [TITLE], [COMPANY], [FULL_ADDRESS], 
                         [PREFIX], [FIRST_NAME], [MIDDLE_NAME], [LAST_NAME], [SUFFIX], [DESIGNATION], [INFORMAL], 
                         [ADDRESS_1], [ADDRESS_2], [CITY], [STATE_PROVINCE], [ZIP], [COUNTRY], [BAR_CODE], [DELEGATE], 
                         [ST_PRINT_COMPANY], [ST_PRINT_TITLE], [ADDRESS_3])
      SELECT ISNULL([ORDER_NUMBER], 0), ISNULL([BADGE_NUMBER], 0), ISNULL([BADGE_TYPE], ''), ISNULL([FULL_NAME], ''), 
             ISNULL([TITLE], ''), ISNULL([COMPANY], ''), ISNULL([FULL_ADDRESS], ''), ISNULL([PREFIX], ''), 
             ISNULL([FIRST_NAME], ''), ISNULL([MIDDLE_NAME], ''), ISNULL([LAST_NAME], ''), ISNULL([SUFFIX], ''), 
             ISNULL([DESIGNATION], ''), ISNULL([INFORMAL], ''), ISNULL([ADDRESS_1], ''), ISNULL([ADDRESS_2], ''), 
             ISNULL([CITY], ''), ISNULL([STATE_PROVINCE], ''), ISNULL([ZIP], ''), ISNULL([COUNTRY], ''), ISNULL([BAR_CODE], ''), 
             [DELEGATE], ISNULL([ST_PRINT_COMPANY], 0), ISNULL([ST_PRINT_TITLE], 0), ISNULL([ADDRESS_3], '')
        FROM Order_Badge_BAK


IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Order_Badge]') AND [name] = N'PK_Order_Badge')
BEGIN
  ALTER TABLE [dbo].[Order_Badge]
  ADD CONSTRAINT PK_Order_Badge PRIMARY KEY CLUSTERED (ORDER_NUMBER, BADGE_NUMBER)
END

IF EXISTS (SELECT 1 FROM sysobjects WHERE type = 'U ' and name = 'Order_Badge')
    GRANT REFERENCES, SELECT, INSERT, DELETE, UPDATE ON Order_Badge TO IMIS

DROP TABLE [dbo].[Order_Badge_BAK]

COMMIT
GO

----------------------------------------------
BEGIN TRANSACTION

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Product_Kit')
BEGIN
    IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Product_Kit_BAK')
    BEGIN
        DROP TABLE [dbo].[Product_Kit_BAK]
    END
    EXEC dbo.asi_RenameTable 'Product_Kit', 'Product_Kit_BAK'
END

SET ANSI_DEFAULTS ON
SET IMPLICIT_TRANSACTIONS OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF

IF NOT EXISTS (SELECT * FROM [dbo].[sysobjects] WHERE [id] = OBJECT_ID(N'[dbo].[Product_Kit]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [dbo].[Product_Kit] (
    [SEQN] int NOT NULL CONSTRAINT [DF_Product_Kit_SEQN] DEFAULT (0),
    [PRODUCT_CODE] varchar(31) NOT NULL CONSTRAINT [DF_Product_Kit_PRODUCT_CODE] DEFAULT (''),
    [ITEM_PRODUCT_CODE] varchar(31) NOT NULL CONSTRAINT [DF_Product_Kit_ITEM_PRODUCT_CODE] DEFAULT (''),
    [ITEM_QUANTITY] decimal(18, 8) NOT NULL CONSTRAINT [DF_Product_Kit_ITEM_QUANTITY] DEFAULT (0),
    [DESCRIPTION] varchar(255) NOT NULL CONSTRAINT [DF_Product_Kit_DESCRIPTION] DEFAULT (''),
    [TIME_STAMP] timestamp NULL
)

END

INSERT INTO Product_Kit ([SEQN], [PRODUCT_CODE], [ITEM_PRODUCT_CODE], [ITEM_QUANTITY], [DESCRIPTION])
    SELECT ISNULL([SEQN], 0), ISNULL([PRODUCT_CODE], ''), ISNULL([ITEM_PRODUCT_CODE], ''), ISNULL([ITEM_QUANTITY], 0), ISNULL([DESCRIPTION], '')
      FROM Product_Kit_BAK


IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Product_Kit]') AND [name] = N'PK_Product_Kit')
BEGIN
  ALTER TABLE [dbo].[Product_Kit]
  ADD CONSTRAINT PK_Product_Kit PRIMARY KEY NONCLUSTERED (SEQN)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Product_Kit]') AND [name] = N'iProduct_KitPRODUCT_CODE')
BEGIN
  CREATE CLUSTERED INDEX iProduct_KitPRODUCT_CODE ON [dbo].[Product_Kit] (PRODUCT_CODE, SEQN)
END

IF NOT EXISTS (SELECT * FROM sysindexes WHERE [id] = OBJECT_ID(N'[dbo].[Product_Kit]') AND [name] = N'iProduct_KitITEM_PRODUCT_CODE')
BEGIN
  CREATE NONCLUSTERED INDEX iProduct_KitITEM_PRODUCT_CODE ON [dbo].[Product_Kit] (ITEM_PRODUCT_CODE)
END

IF EXISTS (SELECT 1 FROM sysobjects WHERE type = 'U ' and name = 'Product_Kit')
    GRANT REFERENCES, SELECT, INSERT, DELETE, UPDATE ON Product_Kit TO IMIS

DROP TABLE [dbo].[Product_Kit_BAK]

COMMIT
GO


