-- i15
------------------------------------------------------
-- Create new "Staff" group to mirror i100 staff group
------------------------------------------------------
DECLARE @now datetime
DECLARE @managerKey uniqueidentifier
DECLARE @groupTypeKey uniqueidentifier
DECLARE @componentKey uniqueidentifier
DECLARE @systemEntityKey uniqueidentifier

DECLARE @allStaffGroupKey uniqueidentifier
DECLARE @casualStaffGroupKey uniqueidentifier
DECLARE @fullStaffGroupKey uniqueidentifier

SELECT @allStaffGroupKey = '3BAF4ED8-ADA2-4F8E-913D-82C6BC809A63'
SELECT @casualStaffGroupKey = '35D9A69C-0E0D-416C-A59D-9A948F6EBBAB'
SELECT @fullStaffGroupKey = '6E52226C-89E7-4682-A7E9-B691C42E4664'

SELECT @now = GETDATE()
SELECT @managerKey = [UserKey] FROM [dbo].[UserMain] WHERE [UserId] = 'MANAGER'
SELECT @groupTypeKey = [GroupTypeKey] FROM [dbo].[GroupTypeRef] WHERE [GroupTypeName] = 'Department' AND [IsSystem] = 1 -- Department group type
SELECT @systemEntityKey = [SystemEntityKey] FROM [dbo].[SystemEntity] WHERE [SystemKeyword] = 'Organization' -- Organization System Entity
SELECT @componentKey = ComponentKey FROM dbo.ComponentRegistry WHERE Name = 'Group' AND InterfaceName = 'BusinessController'

IF NOT EXISTS (SELECT 1 FROM [dbo].[GroupMain] WHERE [GroupKey] = @allStaffGroupKey)
BEGIN
    INSERT INTO [dbo].[UniformRegistry] (UniformKey, ComponentKey)
    VALUES (@allStaffGroupKey, @componentKey)
    
    INSERT INTO [dbo].[GroupMain] ([GroupKey],[Name],[Description],[UpdatedByUserKey],[UpdatedOn],[IsSystem],[IsAutoGenerated],
                                   [GroupTypeKey],[Priority],[OwnerAccessKey],[OverrideOwnerGroupKey],[AccessKey],[CreatedByUserKey],[CreatedOn],
                                   [SystemEntityKey],[IsInvitationOnly],[GroupStatusCode],[IsSimpleGroup],[InheritRolesFlag],[IsSingleRole])
    VALUES (@allStaffGroupKey, N'Staff', N'Group used to assign Staff privileges to its members.', @managerKey, @now, 1, 0,
            @groupTypeKey, NULL, '00000000-0000-0000-0000-000000000E02', NULL, '00000000-0000-0000-0000-000000000F1F', @managerKey, @now,
            @systemEntityKey, 0, N'A', 1, 0, 0);
END;

IF NOT EXISTS (SELECT 1 FROM [dbo].[GroupMain] WHERE [GroupKey] = @casualStaffGroupKey)
BEGIN
    INSERT INTO [dbo].[UniformRegistry] (UniformKey, ComponentKey)
    VALUES (@casualStaffGroupKey, @componentKey)
    
    INSERT INTO [dbo].[GroupMain] ([GroupKey],[Name],[Description],[UpdatedByUserKey],[UpdatedOn],[IsSystem],[IsAutoGenerated],
                                   [GroupTypeKey],[Priority],[OwnerAccessKey],[OverrideOwnerGroupKey],[AccessKey],[CreatedByUserKey],[CreatedOn],
                                   [SystemEntityKey],[IsInvitationOnly],[GroupStatusCode],[IsSimpleGroup],[InheritRolesFlag],[IsSingleRole])
    VALUES (@casualStaffGroupKey, N'Casual Staff', N'Group used to assign Casual Staff privileges to its members.', @managerKey, @now, 1, 0,
            @groupTypeKey, NULL, '00000000-0000-0000-0000-000000000E02', NULL, '00000000-0000-0000-0000-000000000F1F', @managerKey, @now,
            @systemEntityKey, 0, N'A', 1, 0, 0);
END;

IF NOT EXISTS (SELECT 1 FROM [dbo].[GroupMain] WHERE [GroupKey] = @fullStaffGroupKey)
BEGIN
    INSERT INTO [dbo].[UniformRegistry] (UniformKey, ComponentKey)
    VALUES (@fullStaffGroupKey, @componentKey)
    
    INSERT INTO [dbo].[GroupMain] ([GroupKey],[Name],[Description],[UpdatedByUserKey],[UpdatedOn],[IsSystem],[IsAutoGenerated],
                                   [GroupTypeKey],[Priority],[OwnerAccessKey],[OverrideOwnerGroupKey],[AccessKey],[CreatedByUserKey],[CreatedOn],
                                   [SystemEntityKey],[IsInvitationOnly],[GroupStatusCode],[IsSimpleGroup],[InheritRolesFlag],[IsSingleRole])
    VALUES (@fullStaffGroupKey, N'Full Staff', N'Group used to assign Full Staff privileges to its members.', @managerKey, @now, 1, 0,
            @groupTypeKey, NULL, '00000000-0000-0000-0000-000000000E02', NULL, '00000000-0000-0000-0000-000000000F1F', @managerKey, @now,
            @systemEntityKey, 0, N'A', 1, 0, 0);
END;


----------------------------
-- Populate new Staff Groups

-- All Staff
INSERT INTO [dbo].[GroupMember] ([GroupMemberKey],[GroupKey],[MemberContactKey],[IsActive],
                                 [CreatedByUserKey],[CreatedOn],[UpdatedByUserKey],[UpdatedOn])
    SELECT NEWID(), @allStaffGroupKey, um.UserKey, 1,
           @managerKey, @now, @managerKey, @now
      FROM [dbo].[Users] u 
           INNER JOIN [dbo].[UserMain] um ON u.UserId = um.UserId
           LEFT OUTER JOIN [dbo].[GroupMember] gm ON um.[UserKey] = gm.[MemberContactKey] AND gm.[GroupKey] = @allStaffGroupKey
     WHERE um.IsDisabled = 0 AND gm.[MemberContactKey] IS NULL

-- Casual Staff
INSERT INTO [dbo].[GroupMember] ([GroupMemberKey],[GroupKey],[MemberContactKey],[IsActive],
                                 [CreatedByUserKey],[CreatedOn],[UpdatedByUserKey],[UpdatedOn])
    SELECT NEWID(), @casualStaffGroupKey, um.UserKey, 1,
           @managerKey, @now, @managerKey, @now
      FROM [dbo].[Users] u 
           INNER JOIN [dbo].[UserMain] um ON u.UserId = um.UserId
           LEFT OUTER JOIN [dbo].[GroupMember] gm ON um.[UserKey] = gm.[MemberContactKey] AND gm.[GroupKey] = @casualStaffGroupKey
     WHERE u.IsCasualUser = 1 AND um.IsDisabled = 0 AND gm.[MemberContactKey] IS NULL

-- Full Staff
INSERT INTO [dbo].[GroupMember] ([GroupMemberKey],[GroupKey],[MemberContactKey],[IsActive],
                                 [CreatedByUserKey],[CreatedOn],[UpdatedByUserKey],[UpdatedOn])
    SELECT NEWID(), @fullStaffGroupKey, um.UserKey, 1,
           @managerKey, @now, @managerKey, @now
      FROM [dbo].[Users] u 
           INNER JOIN [dbo].[UserMain] um ON u.UserId = um.UserId
           LEFT OUTER JOIN [dbo].[GroupMember] gm ON um.[UserKey] = gm.[MemberContactKey] AND gm.[GroupKey] = @fullStaffGroupKey
     WHERE u.IsCasualUser = 0 AND um.IsDisabled = 0 AND gm.[MemberContactKey] IS NULL
GO

----------------------------------------------------------------
-- Create new Access Areas for various Staff types, Full Control
----------------------------------------------------------------
DECLARE @accessKey uniqueidentifier
DECLARE @allStaffGroupKey uniqueidentifier
DECLARE @casualStaffGroupKey uniqueidentifier
DECLARE @fullStaffGroupKey uniqueidentifier
DECLARE @administratorUserKey uniqueidentifier
DECLARE @administratorRoleKey uniqueidentifier
DECLARE @contentAdminRoleKey uniqueidentifier
-- Staff Group Keys
SELECT @allStaffGroupKey = '3BAF4ED8-ADA2-4F8E-913D-82C6BC809A63'
SELECT @casualStaffGroupKey = '35D9A69C-0E0D-416C-A59D-9A948F6EBBAB'
SELECT @fullStaffGroupKey = '6E52226C-89E7-4682-A7E9-B691C42E4664'
-- User & Role Keys
SELECT @administratorUserKey = [UserKey] FROM [dbo].[UserMain] WHERE [UserId] = 'ADMINISTRATOR'
IF @administratorUserKey IS NULL SELECT @administratorUserKey = [UserKey] FROM [dbo].[UserMain] WHERE [UserId] = 'MANAGER'
SELECT @administratorRoleKey = [RoleKey] FROM [dbo].[RoleMain] WHERE [Name] = 'SysAdmin'
SELECT @contentAdminRoleKey = [RoleKey] FROM [dbo].[RoleMain] WHERE [Name] = 'Content Administrator'

------------------------------------
-- All Staff Full Control

SET @accessKey = '00000000-0000-0000-0000-000000000CA1'
-- Create AccessMain Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessMain] WHERE [AccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessMain] ([AccessKey], [AccessScope], [CreatedByUserKey], [CreatedOn], [UpdatedByUserKey], [UpdatedOn])
    VALUES (@accessKey, 'Area', @administratorUserKey, '20120822 12:00:00', @administratorUserKey, '20120822 12:00:00')
-- Create AccessItem Entries
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessItem] WHERE [AccessKey] = @accessKey)
BEGIN
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [GroupKey])
    VALUES (@accessKey, @allStaffGroupKey, 31, @allStaffGroupKey)
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [RoleKey])
    VALUES (@accessKey, @administratorRoleKey, 1, @administratorRoleKey)
END
-- Create AccessArea Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessArea] WHERE [ProtectedAccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessArea] ([AccessAreaKey], [Name], [Description], [IsSystem], [ProtectedAccessKey], [UpdatedByUserKey], [UpdatedOn], [IsSharedACLOnly], [CreatedByUserKey], [CreatedOn])
    VALUES (@accessKey, 'All Staff Full Control', 'All Staff Full Control', 1, @accessKey, @administratorUserKey, '20120822 12:00:00', 1, @administratorUserKey, '20120822 12:00:00')

------------------------------------
-- All Staff Full Control+CA
SET @accessKey = '00000000-0000-0000-CA00-000000000CA1'

-- Create AccessMain Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessMain] WHERE [AccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessMain] ([AccessKey], [AccessScope], [CreatedByUserKey], [CreatedOn], [UpdatedByUserKey], [UpdatedOn])
    VALUES (@accessKey, 'Area', @administratorUserKey, '20120822 12:00:00', @administratorUserKey, '20120822 12:00:00')
-- Create AccessItem Entries
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessItem] WHERE [AccessKey] = @accessKey)
BEGIN
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [GroupKey])
    VALUES (@accessKey, @allStaffGroupKey, 31, @allStaffGroupKey)
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [RoleKey])
    VALUES (@accessKey, @administratorRoleKey, 1, @administratorRoleKey)
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [RoleKey])
    VALUES (@accessKey, @contentAdminRoleKey, 1, @contentAdminRoleKey)
END
-- Create AccessArea Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessArea] WHERE [ProtectedAccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessArea] ([AccessAreaKey], [Name], [Description], [IsSystem], [ProtectedAccessKey], [UpdatedByUserKey], [UpdatedOn], [IsSharedACLOnly], [CreatedByUserKey], [CreatedOn],[IsContentACL])
    VALUES (@accessKey, 'CA+All Staff Full Control', 'All Staff Full Control', 1, @accessKey, @administratorUserKey, '20120822 12:00:00', 1, @administratorUserKey, '20120822 12:00:00', 1)


------------------------------------
-- Casual Staff Full Control

SET @accessKey = '00000000-0000-0000-0000-000000000CC1'
-- Create AccessMain Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessMain] WHERE [AccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessMain] ([AccessKey], [AccessScope], [CreatedByUserKey], [CreatedOn], [UpdatedByUserKey], [UpdatedOn])
    VALUES (@accessKey, 'Area', @administratorUserKey, '20120822 12:00:00', @administratorUserKey, '20120822 12:00:00')
-- Create AccessItem Entries
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessItem] WHERE [AccessKey] = @accessKey)
BEGIN
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [GroupKey])
    VALUES (@accessKey, @casualStaffGroupKey, 31, @casualStaffGroupKey)
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [RoleKey])
    VALUES (@accessKey, @administratorRoleKey, 1, @administratorRoleKey)
END
-- Create AccessArea Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessArea] WHERE [ProtectedAccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessArea] ([AccessAreaKey], [Name], [Description], [IsSystem], [ProtectedAccessKey], [UpdatedByUserKey], [UpdatedOn], [IsSharedACLOnly], [CreatedByUserKey], [CreatedOn])
    VALUES (@accessKey, 'Casual Staff Full Control', 'Casual Staff Full Control', 1, @accessKey, @administratorUserKey, '20120822 12:00:00', 1, @administratorUserKey, '20120822 12:00:00')

------------------------------------
-- Casual Staff Full Control+CA
SET @accessKey = '00000000-0000-0000-CA00-000000000CC1'

-- Create AccessMain Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessMain] WHERE [AccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessMain] ([AccessKey], [AccessScope], [CreatedByUserKey], [CreatedOn], [UpdatedByUserKey], [UpdatedOn])
    VALUES (@accessKey, 'Area', @administratorUserKey, '20120822 12:00:00', @administratorUserKey, '20120822 12:00:00')
-- Create AccessItem Entries
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessItem] WHERE [AccessKey] = @accessKey)
BEGIN
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [GroupKey])
    VALUES (@accessKey, @casualStaffGroupKey, 31, @casualStaffGroupKey)
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [RoleKey])
    VALUES (@accessKey, @administratorRoleKey, 1, @administratorRoleKey)
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [RoleKey])
    VALUES (@accessKey, @contentAdminRoleKey, 1, @contentAdminRoleKey)
END
-- Create AccessArea Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessArea] WHERE [ProtectedAccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessArea] ([AccessAreaKey], [Name], [Description], [IsSystem], [ProtectedAccessKey], [UpdatedByUserKey], [UpdatedOn], [IsSharedACLOnly], [CreatedByUserKey], [CreatedOn],[IsContentACL])
    VALUES (@accessKey, 'CA+Casual Staff Full Control', 'Casual Staff Full Control', 1, @accessKey, @administratorUserKey, '20120822 12:00:00', 1, @administratorUserKey, '20120822 12:00:00', 1)


------------------------------------
-- Full Staff Full Control

SET @accessKey = '00000000-0000-0000-0000-000000000CF1'
-- Create AccessMain Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessMain] WHERE [AccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessMain] ([AccessKey], [AccessScope], [CreatedByUserKey], [CreatedOn], [UpdatedByUserKey], [UpdatedOn])
    VALUES (@accessKey, 'Area', @administratorUserKey, '20120822 12:00:00', @administratorUserKey, '20120822 12:00:00')
-- Create AccessItem Entries
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessItem] WHERE [AccessKey] = @accessKey)
BEGIN
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [GroupKey])
    VALUES (@accessKey, @fullStaffGroupKey, 31, @fullStaffGroupKey)
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [RoleKey])
    VALUES (@accessKey, @administratorRoleKey, 1, @administratorRoleKey)
END
-- Create AccessArea Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessArea] WHERE [ProtectedAccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessArea] ([AccessAreaKey], [Name], [Description], [IsSystem], [ProtectedAccessKey], [UpdatedByUserKey], [UpdatedOn], [IsSharedACLOnly], [CreatedByUserKey], [CreatedOn])
    VALUES (@accessKey, 'Full Staff Full Control', 'Full Staff Full Control', 1, @accessKey, @administratorUserKey, '20120822 12:00:00', 1, @administratorUserKey, '20120822 12:00:00')

------------------------------------
-- Full Staff Full Control+CA
SET @accessKey = '00000000-0000-0000-CA00-000000000CF1'

-- Create AccessMain Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessMain] WHERE [AccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessMain] ([AccessKey], [AccessScope], [CreatedByUserKey], [CreatedOn], [UpdatedByUserKey], [UpdatedOn])
    VALUES (@accessKey, 'Area', @administratorUserKey, '20120822 12:00:00', @administratorUserKey, '20120822 12:00:00')
-- Create AccessItem Entries
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessItem] WHERE [AccessKey] = @accessKey)
BEGIN
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [GroupKey])
    VALUES (@accessKey, @fullStaffGroupKey, 31, @fullStaffGroupKey)
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [RoleKey])
    VALUES (@accessKey, @administratorRoleKey, 1, @administratorRoleKey)
    INSERT INTO [dbo].[AccessItem] ([AccessKey], [Grantee], [Permission], [RoleKey])
    VALUES (@accessKey, @contentAdminRoleKey, 1, @contentAdminRoleKey)
END
-- Create AccessArea Entry
IF NOT EXISTS (SELECT 1 FROM [dbo].[AccessArea] WHERE [ProtectedAccessKey] = @accessKey)
    INSERT INTO [dbo].[AccessArea] ([AccessAreaKey], [Name], [Description], [IsSystem], [ProtectedAccessKey], [UpdatedByUserKey], [UpdatedOn], [IsSharedACLOnly], [CreatedByUserKey], [CreatedOn],[IsContentACL])
    VALUES (@accessKey, 'CA+Full Staff Full Control', 'Full Staff Full Control', 1, @accessKey, @administratorUserKey, '20120822 12:00:00', 1, @administratorUserKey, '20120822 12:00:00', 1)
GO



