
UPDATE [dbo].[DocumentMain] SET [DocumentStatusCode] = 10 
 WHERE [DocumentName] IN ('CsActivityBasic','CsAsiNrdsAssociation','CsAsiNrdsMember','CsAsiNrdsMemberDemographic','CsAsiNrdsMemberDesignation','CsAsiNrdsMemberEducation','CsAsiNrdsMemberFinancial','CsAsiNrdsMemberSupplemental','CsAsiNrdsOffice','CsAsiNrdsOfficeSupplemental','CsName_Indexes','CsName_Staff','CsNameFin','CsSubscriptionsChapters','CsTerms','CultivatingFor','CultivationActivity','ExperienceUnit','FundraisingProfileDonorData','GiftArray','IndividualExternalNetworks','InvoiceSummary','NrdsLog','Profile_Page','SocialNetworkLinks','Solicitors','SystemConfigXml','URLMappingTypeRef') 
   AND [DocumentTypeCode] = 'BOD' AND [DocumentStatusCode] = 40

go

UPDATE [dbo].[DocumentMain] SET [DocumentStatusCode] = 10 
 WHERE [DocumentName] IN ('ActionPlan','Activity','Address','AddressCategoryRef','AddressFormatRef','AddressPurposeRef','AddressStatusRef','AddressTypeRef','Appeal','Campaign','CampaignParticipation','CertificationModule','CertificationModuleProduct','CertificationProgram','CertificationProgramProduct','Committee','CommunicationReasonRef','CompanyNaicSic','Contact','ContactAddress','ContactBiography','ContactDuplicateCheckFormula','ContactEducation','ContactLog','ContactOffering','ContactPicture','ContactSalutation','ContactSkill','ContactStatusRef','CountryRef','CsActivity','CsActivityTypes','CsAddress','CsAppeal','CsCalls','CsCampaign','CsCommittee','CsCommitteeCode','CsCommitteeMember','CsCommitteeMemberGroup','CsCommitteePosition','CsContact','CsContactRelatedCompany','CsCountryNames','CsDonations','CsDonationsDetail','CsDonorData','CsDuesHistory','CsEvent','CsEventHistory','CsExchangeRate','CsFunction','CsFunctionFees','CsGeneralLookupTables','CsGenTablesUnion','CsInventory','CsInvoice','CsIsoCurrencyCodes','CsLetters','CsMatchingPlans','CsMemberType','CsName_FR','CsName_Lookup','CsName_TabTest','CsNameLog','CsNameNote','CsNameUser','CsNotificationList','CsOrderHistory','CsOrderLines','CsOrders','CsOrderType','CsOrg_Control','CsPledges','CsProduct','CsProductCategory','CsProductType','CsRegFunctions','CsRegistrantClasses','CsRegistration','CsRelationship','CsRelationshipTypes','CsSalesHistory','CsSalutations','CsSolicitorData','CsStaffUser','CsStateProvinceCodes','CsSubscriptions','CsSystemParams','CsTransSoftCredit','CsWebSecurityGroup','CsWebUser','Document','Donation','ExperienceCountSummary','ExperienceDefinition','FinancialEntityDueTo','Fund','FundFamilyRef','FundFundType','Gift','GiftAidDeclaration','GiftHistory','GiftHistorySummary','GiftsReceived','GroupMember','GroupMemberDetail','GroupTypeRef','GroupTypeRole','LicenseMain','LicenseMapMaster','MatchingGiftPlanTypeRef','MemorialTribute','NavigationPane','NetContact','Offering','Opportunity','OpportunityType','OrderCategory','Package','ParticipantRoster','PrefixRef','ProcessTypeDefaultOwnerAllUsers','Program','ProgramGroup','RecurringDonationCommitment','RecurringDonationExpectedPayment','RecurringDonationExpectedPaymentSetList','RegisteredComponent','RelationshipTypeRef','RFMAnalysis','Role','RoundingMultipleRef','RuleFilter','SalutationRef','SeasonalFullAddress','SegmentationDef','SegmentationJob','Solicitation','SourceCode','SourceList','StoreFeaturedProducts','SuffixRef','Supplement','SystemEntity','TaskItem','TaxAuthorityCategory','TaxAuthorityFinancialEntity','TaxScheduleAuthority','URLMapping','User','WorkflowInstanceReport','WorkflowServiceWorkerReport') 
   AND [DocumentTypeCode] = 'BOD' AND [DocumentStatusCode] = 40

go

